# Generated by Django 4.1.7 on 2023-03-23 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_created_at_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 23, 15, 44, 49, 733653, tzinfo=datetime.timezone.utc)),
        ),
    ]
