# Generated by Django 4.1.7 on 2023-03-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
